# touhou rss collection 

Articles:
  知乎话题-东方Project: https://rsshub.5l.re/zhihu/topic/19701004
  # 文文最速新闻: https://www.touhou.cc/bbs/forum.php?mod=forumdisplay&fid=48&mod=rss
  文文最速新闻: https://rsshub.5l.re/discuz/https%3A%2F%2Fwww.touhou.cc%2Fbbs%2Fforum.php%3Fmod=forumdisplay%26fid=48
  魔女的茶会: https%3A%2F%2Fbbs.nyasama.com%2Fforum.php%3Fmod=forumdisplay%26fid=4
  无蛋黄_METAEGO: https://rsshub.5l.re/bilibili/user/article/152386806
  Pak长: https://rsshub.5l.re/bilibili/user/article/115945
  东方吧: https://rsshub.5l.re/baidu/tieba/forum/%E4%B8%9C%E6%96%B9%E5%90%A7
  充满魔力的土地下: http://touhoudog.net/feed/

Videos:
  # b站收藏夹
  五郎-东方: https://rsshub.5l.re/bilibili/fav/359079394/2299444994
  五郎-东方动画: https://rsshub.5l.re/bilibili/fav/359079394/2320517394
  御坂14363号-东方: https://rsshub.5l.re/bilibili/fav/699221292/1703917092
  东方音像馆: https://rsshub.5l.re/bilibili/user/dynamic/630991474
  【东方音像馆】动画: https://rsshub.5l.re/bilibili/fav/630991474/2039128274
  #【东方音像馆】原作背景设定解析视频: https://rsshub.5l.re/bilibili/fav/630991474/1531327474
  【东方同人】手书/动画/MMD/游戏: https://rsshub.5l.re/bilibili/fav/630991474/2058051274
  【东方音像馆】捏他: https://rsshub.5l.re/bilibili/fav/630991474/1531504474
  东方同人视频神中神: https://rsshub.5l.re/bilibili/fav/630991474/2052123874
  东方同人视频佳作推荐: https://rsshub.5l.re/bilibili/fav/630991474/2045619274
  【东方音像馆】Bad Apple: https://rsshub.5l.re/bilibili/fav/630991474/1532146474
  【东方音像馆】MC联动: https://rsshub.5l.re/bilibili/fav/630991474/1534255574
  【东方音像馆】整活: https://rsshub.5l.re/bilibili/fav/630991474/1531517074
  【东方音像馆】MMD舞蹈: https://rsshub.5l.re/bilibili/fav/630991474/1531422574
  【东方音像馆】MMD日常: https://rsshub.5l.re/bilibili/fav/630991474/1531269674
  【东方音像馆】MMD剧情: https://rsshub.5l.re/bilibili/fav/630991474/1531332674
  【东方音像馆】MMD长篇: https://rsshub.5l.re/bilibili/fav/630991474/1531393074
  【东方音像馆】MMD中篇: https://rsshub.5l.re/bilibili/fav/630991474/1534416774
  【东方音像馆】MMD短篇: https://rsshub.5l.re/bilibili/fav/630991474/1531329274
  【东方音像馆】日语MMD: https://rsshub.5l.re/bilibili/fav/630991474/1531155474
  【东方音像馆】3D: https://rsshub.5l.re/bilibili/fav/630991474/1534398374
  【东方音像馆】手书剧情: https://rsshub.5l.re/bilibili/fav/630991474/1534319574
  【东方音像馆】手书: https://rsshub.5l.re/bilibili/fav/630991474/1531254974
  【东方音像馆】MAD静止系PV: https://rsshub.5l.re/bilibili/fav/630991474/1531324574


  # b站动态
  东方音像馆: https://rsshub.5l.re/bilibili/user/dynamic/630991474
  曦阳_231-MMD: https://rsshub.5l.re/bilibili/user/dynamic/696721978
  乌冬院-MMD: https://rsshub.5l.re/bilibili/user/dynamic/21529645
  Zhipr-MMD: https://rsshub.5l.re/bilibili/user/dynamic/9496794
  博丽x海苔-MMD: https://rsshub.5l.re/bilibili/user/dynamic/41039728
  千代敏儿-coser: https://rsshub.5l.re/bilibili/user/dynamic/343896757
  鹿野修仙-手书: https://rsshub.5l.re/bilibili/user/dynamic/2746011
  幻想乡的新月-搬运工: https://rsshub.5l.re/bilibili/user/dynamic/149592
  丶惟茉-中国同人社团: https://rsshub.5l.re/bilibili/user/dynamic/2141593
  R十寻-搬运工: https://rsshub.5l.re/bilibili/user/dynamic/942357

  # b站合集
  芊年人间-东浅语: https://rsshub.5l.re/bilibili/user/collection/204706570/176804
  芙兰档案: https://rsshub.5l.re/bilibili/user/collection/1345435780/902426
  筱瑶-东方安利: https://rsshub.5l.re/bilibili/user/collection/352163411/394719
  Z一LGW-猩东方: https://rsshub.5l.re/bilibili/user/collection/11007230/45383
  Z一LGW-来世炸了幻想乡: https://rsshub.5l.re/bilibili/user/channel/11007230/541095
  Z一LGW-全人类的飞上天: https://rsshub.5l.re/bilibili/user/channel/11007230/541094
  Z一LGW-梗东方: https://rsshub.5l.re/bilibili/user/collection/11007230/819078
  Z一LGW-聊东方了: https://rsshub.5l.re/bilibili/user/collection/11007230/2342
  keiko_惠子-东方手书: https://rsshub.5l.re/bilibili/user/collection/200090/20026
  香芋-Tarona-东方同人: https://rsshub.5l.re/bilibili/user/collection/2270777/209187
  MC3D东方系列: https://rsshub.5l.re/bilibili/user/collection/110924762/211484
  东方系列MV 4K重置: https://rsshub.5l.re/bilibili/user/collection/44110686/1237567
  囧仙-京都幻想剧团: https://rsshub.5l.re/bilibili/user/collection/12246/364922

  # niconico-东方tag
  niconico-東方: https://www.nicovideo.jp/tag/%25E6%259D%25B1%25E6%2596%25B9?sort=f&rss=2.0&lang=ja-jp

Music:
  # b站收藏夹
  五郎-东方音乐: https://rsshub.5l.re/bilibili/fav/359079394/2293459894
  御坂14363号-东方音乐: https://rsshub.5l.re/bilibili/fav/699221292/1699573092
  【东方音像馆】同人音乐: https://rsshub.5l.re/bilibili/fav/630991474/1531256274
  【东方同音录】温暖的神社｜曲风大全: https://rsshub.5l.re/bilibili/fav/630991474/1381836274
  【东方同音录】温暖的神社｜热门曲: https://rsshub.5l.re/bilibili/fav/630991474/1450130374
  【东方同音录】温暖的神社｜风格改编: https://rsshub.5l.re/bilibili/fav/630991474/1382777374
  【东方同音录】温暖的神社｜拼合: https://rsshub.5l.re/bilibili/fav/630991474/1381763674
  【东方同音录】温暖的神社｜良曲萃集: https://rsshub.5l.re/bilibili/fav/630991474/1382980374
  【东方同音录】温暖的神社｜创意: https://rsshub.5l.re/bilibili/fav/630991474/1383201874
  【东方音乐】原曲同人串烧/相关/分析: https://rsshub.5l.re/bilibili/fav/630991474/2057360574
  【原曲】再翻译/分析: https://rsshub.5l.re/bilibili/fav/630991474/2057763174
  



  # b站动态
  触手猴-钢琴演奏: https://rsshub.5l.re/bilibili/user/dynamic/489391680
  筱瑶-钢琴演奏: https://rsshub.5l.re/bilibili/user/dynamic/352163411
  11是谁啊-同人音乐: https://rsshub.5l.re/bilibili/user/dynamic/1664494
  RickyRister-同人音乐: https://rsshub.5l.re/bilibili/user/dynamic/393639419
  肥兔菌-东方音乐: https://rsshub.5l.re/bilibili/user/dynamic/297656522
  幽闭星光-音乐社团: https://rsshub.5l.re/bilibili/user/dynamic/23052222
  夏天的奇妙-口琴演奏: https://rsshub.5l.re/bilibili/user/dynamic/90398168
  野兽钢琴-钢琴改编: https://rsshub.5l.re/bilibili/user/dynamic/3493264896296985
  秦心酱-钢琴演奏: https://rsshub.5l.re/bilibili/user/dynamic/475040596
  枫林长笛-长笛演奏: https://rsshub.5l.re/bilibili/user/dynamic/476734435
  深蓝水下苍苍梦-同人音乐: https://rsshub.5l.re/bilibili/user/dynamic/10942124
  YaboiMatoi-重金属改编: https://rsshub.5l.re/bilibili/user/dynamic/1459658277
  红维流星-交响改编: https://rsshub.5l.re/bilibili/user/dynamic/6675622
  头铁的辉夜-音乐传教: https://rsshub.5l.re/bilibili/user/dynamic/233591
  某猹OS-东方风作曲: https://rsshub.5l.re/bilibili/user/dynamic/15976617

  # b站合集
  筱瑶-东方扒谱: https://rsshub.5l.re/bilibili/user/channel/352163411/1672205
  筱瑶-东方暴力传教: https://rsshub.5l.re/bilibili/user/channel/352163411/1672203
  幻梦流光交响社-东方旧作: https://rsshub.5l.re/bilibili/user/channel/27709843/446179
  榆木华-东方组曲: https://rsshub.5l.re/bilibili/user/channel/3663104/272051
  筱瑶-东方超还原の扒谱: https://rsshub.5l.re/bilibili/user/collection/352163411/46832
  Yoshika_DK-管乐组曲: https://rsshub.5l.re/bilibili/user/collection/39386600/611627
  魔法少女wifi酱-东方project: https://rsshub.5l.re/bilibili/user/collection/14802357/220526
  筱瑶-东方战斗曲: https://rsshub.5l.re/bilibili/user/collection/352163411/439252
  筱瑶-东方组曲: https://rsshub.5l.re/bilibili/user/collection/352163411/307424
  东方永夜抄-钢琴演奏: https://rsshub.5l.re/bilibili/user/channel/475040596/595318
  暁Records-PV: https://rsshub.5l.re/bilibili/user/collection/448823/956606
  囧仙-幻奏盛宴: https://rsshub.5l.re/bilibili/user/channel/12246/894824

  # 网易云:
  上海爱丽丝幻乐团_ZUN-网易云: https://rsshub.5l.re/163/music/artist/15345
  TAMUISC-网易云: https://rsshub.5l.re/163/music/artist/21967
  Foxtail-Grass Studio-网易云: https://rsshub.5l.re/163/music/artist/19481
  凋叶棕-网易云: https://rsshub.5l.re/163/music/artist/21981
  狐の工作室-网易云: https://rsshub.5l.re/163/music/artist/22433
  はちみつれもん-网易云: https://rsshub.5l.re/163/music/artist/19774
  舞風-网易云: https://rsshub.5l.re/163/music/artist/20554
  流派未月亭-网易云: https://rsshub.5l.re/163/music/artist/1050749
  交響アクティブNEETs-网易云: https://rsshub.5l.re/163/music/artist/11996090
  无蛋黄_METAEGO-网易云歌单: https://rsshub.5l.re/163/music/user/playlist/497089697
  东方同音鉴-网易云歌单: https://rsshub.5l.re/163/music/user/playlist/1905611511

Photos:
  # pixiv
  pixiv-touhou: https://rsshub.5l.re/pixiv/search/touhou
  pixiv-核燃黑猫: https://rsshub.5l.re/pixiv/user/1408324
  pixiv-oO大黄Oo: https://rsshub.5l.re/pixiv/user/9892346

  # b站动态
  剑の冰精-同人漫画: https://rsshub.5l.re/bilibili/user/dynamic/384431765
  百流夜-有声漫画: https://rsshub.5l.re/bilibili/user/dynamic/195533478
  跃亮-有声漫画: https://rsshub.5l.re/bilibili/user/dynamic/3170013
  清澈雨滴-同人漫画: https://rsshub.5l.re/bilibili/user/dynamic/503150289
  炸鸡QwQ-配音手书: https://rsshub.5l.re/bilibili/user/dynamic/1345435780

Games:
  # steam
  官方系列作品-Steam: https://rsshub.5l.re/steam/search/developer=%25E4%25B8%258A%25E6%25B5%25B7%25E3%2582%25A2%25E3%2583%25AA%25E3%2582%25B9%25E5%25B9%25BB%25E6%25A8%2582%25E5%259B%25A3&ndl=1
  东方同人作品-Steam: https://rsshub.5l.re/steam/search/term=touhou&ndl=1
  
  # b站
  东方夜雀食堂: https://rsshub.5l.re/bilibili/user/collection/86865890/2755
  东方妖灵传: https://rsshub.5l.re/bilibili/user/collection/2673367/1200786
  The_495th_Comple: https://rsshub.5l.re/bilibili/user/dynamic/1629262586
  东方冰之勇者记: https://rsshub.5l.re/bilibili/user/collection/1079825019/564130
  WILDLOTUS: https://rsshub.5l.re/bilibili/user/dynamic/1561810545
  【东方音像馆】游戏魔改/mod: https://rsshub.5l.re/bilibili/fav/630991474/1531254874
  【东方音像馆】原作STG: https://rsshub.5l.re/bilibili/fav/630991474/1534837874
  【东方音像馆】同人游戏: https://rsshub.5l.re/bilibili/fav/630991474/1531509874

Clubs:
  # Twitter
  博麗神主-Twitter: https://rsshub.5l.re/twitter/user/korindo

  # b站动态
  森罗万象-音乐社团: https://rsshub.5l.re/bilibili/user/dynamic/165906284
  瑶山百灵-音乐社团: https://rsshub.5l.re/bilibili/user/dynamic/210232
  幻梦流光交响社-音乐社团: https://rsshub.5l.re/bilibili/user/dynamic/27709843
  囧仙-远古の神: https://rsshub.5l.re/bilibili/user/dynamic/12246
  伊吹小秋-搬运工: https://rsshub.5l.re/bilibili/user/dynamic/448823
  因幡帝汉化组: https://rsshub.5l.re/bilibili/user/dynamic/32589387
  胡逆天-爱好者: https://rsshub.5l.re/bilibili/user/dynamic/3621415
  Z一LGW-传教士: https://rsshub.5l.re/bilibili/user/dynamic/11007230

  # 网站
  THCSC: https://www.thclubsc.cn/ewr-porta/index.rss
  yondervoice: http://yondervoice.net/?feed=rss2
  京都幻想剧团: http://kyotofantasytroupe.net/feed

Develops:
  # Github
  Touhou-Public-Repo: https://rsshub.5l.re/github/repos/touhou-public
  touhou-midi-collection: https://github.com/AyHa1810/touhou-midi-collection/commits.atom

Webiste:
  touhou.cc BBS: https://www.touhou.cc/bbs/?mod=rss

Owner:
  SMGoroBlog: https://blog.imc.re/atom.xml
  五郎のb站动态: /bilibili/user/dynamic/359079394
  五郎の知乎动态: /zhihu/people/activities/smgoro
  五郎の爱发电动态: /afdian/dynamic/@SummerGoro


